REPORTERS_MARKDOWN_TYPE: simple
PRINT_ALPACA: false
GITHUB_COMMENT_REPORTER: true
DISABLE_LINTERS:
- SPELL_LYCHEE
- REPOSITORY_KICS
FILTER_REGEX_EXCLUDE: (.github/workflows/mega-linter.yml|)
SPELL_FILTER_REGEX_EXCLUDE: (?i)\b(KICS|Softchoice)\b
