trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bicep/*.bicep

name: Deploy Bicep Stack

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: stackName
  displayName: Stack Name
  default: myStack
- name: nameString
  displayName: Name String
  default: myai900
- name: location
  displayName: Resource Location
  default: eastus
  values:
  - eastus

variables:
  serviceConnection: 'devops-bicep-ai900-service-connection'
  resourceGroupLocation: ${{ parameters.location }}
  templateFile: 'bicep/main.bicep'

steps:
  - task: AzureCLI@2
    displayName: Deploy Stack
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az stack sub create -f $(templateFile) \
          --location $(resourceGroupLocation) --name ${{ parameters.stackName }} \
          --delete-all --deny-settings-mode none \
          -p nameString=${{ parameters.nameString }} resourceGroupLocation=$(resourceGroupLocation)